CREATE TABLE complaints (
    id INT AUTO_INCREMENT PRIMARY KEY,
    reference_number VARCHAR(20) NOT NULL UNIQUE,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    selected_category VARCHAR(50) NULL,
    detected_category VARCHAR(50) NOT NULL DEFAULT 'Unclassified',
    location VARCHAR(150) NULL,
    incident_date DATE NULL,
    is_immediate_danger TINYINT(1) NOT NULL DEFAULT 0,
    affects_multiple_students TINYINT(1) NOT NULL DEFAULT 0,
    was_previously_reported TINYINT(1) NOT NULL DEFAULT 0,
    is_anonymous TINYINT(1) NOT NULL DEFAULT 0,
    student_name VARCHAR(100) NULL,
    student_number VARCHAR(50) NULL,
    student_email VARCHAR(150) NULL,
    urgency_score INT NOT NULL DEFAULT 0,
    priority ENUM('Low', 'Medium', 'High', 'Critical') NOT NULL DEFAULT 'Low',
    assigned_department VARCHAR(100) NOT NULL DEFAULT '',
    is_sensitive TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('Submitted', 'Under Review', 'In Progress', 'Resolved') NOT NULL DEFAULT 'Submitted',
    submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    response_deadline DATETIME NULL,
    resolved_at DATETIME NULL
);